#!/bin/bash
PASSWD="/etc/passwd"
LOGIN_DEFS="/etc/login.defs"
PASSWORD_POLICY="/etc/pam.d/system-auth"
LOGIN="$PASSWORD_POLICY"
AUDIT_RULE="/etc/audit/audit.rules"
PROC_NET_DEV="/proc/net/dev"
IPTABLES="/etc/sysconfig/iptables"
NTP="/etc/ntp.conf"
LOGWATCH="/etc/cron.daily/0logwatch"
echo "{--Checking file--}"
ls $PASSWD
ls $LOGIN_DEFS
ls $PASSWORD_POLICY
ls $LOGIN
ls $AUDIT_RULE
ls $PROC_NET_DEV
ls $NTP
echo "{----}"
echo "{--OS infomation--}" && rpm -q centos-release && ip address|grep "inet ";echo "{----}"
echo "{--01--}" && cat $PASSWD|awk -F: '($3=="0"){print $1}';echo "{----}"
echo "{--02--}" &&  awk -F: '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="halt" && $1!~/^\+/ && $3<'"$(awk '/^\s*UID_MIN/{print $2}' $LOGIN_DEFS)"' && $7!="'"$(which nologin)"'" && $7!="/bin/false") {print $1}' $PASSWD|while read -r item;do printf "$item|";done|sed 's/|$//g';echo;echo "{----}"
echo "{--03--}" && grep -E "/var/log/messages|/var/log/secure|/var/log/maillog|/var/log/spooler|/var/log/cron" /etc/logrotate.d/syslog|while read -r item;do printf "$item|";done|sed 's/|$//g';echo;echo "{----}"
echo "{--04--}" && ls –la $LOGWATCH |grep "0logwatch->/usr/share/logwatch/scripts/logwatch.pl"|wc -l;echo "{----}"
echo "{--05--}" && cat $PASSWD|awk -F: '($2==""){print}';echo "{----}"
echo "{--06--}" && cat $PASSWD|awk -F: '($2!="x"){print}';echo "{----}"
echo "{--07--}" && cat $LOGIN_DEFS|grep ^PASS_MIN_DAYS;echo "{----}"
echo "{--08--}" && cat $LOGIN_DEFS|grep ^PASS_WARN_AGE;echo "{----}"
echo "{--09--}" && cat $LOGIN_DEFS|grep ^PASS_MAX_DAYS;echo "{----}"
echo "{--10--}" && cat $LOGIN_DEFS|grep ^PASS_MIN_LEN;echo "{----}"
echo "{--11--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep retry";echo "{----}"
echo "{--12--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep credit";echo "{----}"
echo "{--13--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep ucredit";echo "{----}"
echo "{--14--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep lcredit";echo "{----}"
echo "{--15--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep ocredit";echo "{----}"
echo "{--16--}" && cat $PASSWORD_POLICY|grep "pam_cracklib.so|grep difok";echo "{----}"
echo "{--17--}" && cat $PASSWORD_POLICY|grep "remember=24";echo "{----}"
echo "{--18--}" && authconfig --test | grep hashing;echo "{----}"
echo "{--19--}" && cat $LOGIN|grep "pam_tally2.so"|grep deny;echo "{----}"
echo "{--20--}" && chkconfig --list auditd|grep ^auditd;echo "{----}"
echo "{--21--}" && cat $AUDIT_RULE|grep -E "\-k time-change";echo "{----}"
echo "{--22--}" && cat $AUDIT_RULE|grep -E "\-k identity";echo "{----}"
echo "{--23--}" && cat $AUDIT_RULE|grep -E "\-k system-locale";echo "{----}"
echo "{--24--}" && cat $AUDIT_RULE|grep -E "\-k MAC-policy";echo "{----}"
echo "{--25--}" && cat $AUDIT_RULE|grep -E "\-k perm_mod";echo "{----}"
echo "{--26--}" && cat $AUDIT_RULE|grep -E "\-k access";echo "{----}"
echo "{--27--}" && find `blkid |awk -F: '{print $1}'` -xdev \( -perm -4000 -o -perm -2000 \) -type f;cat $AUDIT_RULE|grep -E "\-k privileged";echo "{----}"
echo "{--28--}" && cat $AUDIT_RULE|grep -E "\-k export";echo "{----}"
echo "{--29--}" && cat $AUDIT_RULE|grep -E "\-k delete";echo "{----}"
echo "{--30--}" && cat $AUDIT_RULE|grep -E "\-k actions";echo "{----}"
echo "{--31--}" && cat $AUDIT_RULE|grep -E "\-k modules";echo "{----}"
echo "{--32--}" && cat $AUDIT_RULE|tail -n1;echo "{----}"
echo "{--33--}" && cat $AUDIT_RULE|grep -E "\-k logins";echo "{----}"
echo "{--34--}" && cat $AUDIT_RULE|grep -E "\-k session";echo "{----}"
echo "{--35--}" && gconftool-2 -R /apps/gnome-screensaver;echo "{----}"
echo "{--36--}" && rpm -q iptables|grep ^iptables;echo "{----}"
echo "{--37--}" && iptables -L|grep -E "Chain INPUT|Chain FORWARD|Chain OUTPUT";echo "{----}"
echo "{--38--}" && sysctl net.ipv4.ip_forward;echo "{----}"
echo "{--39--}" && sysctl net.ipv4.conf.all.send_redirects;echo "{----}"
echo "{--40--}" && sysctl net.ipv4.conf.default.send_redirects;echo "{----}"
echo "{--41--}" && sysctl net.ipv4.conf.all.secure_redirects;echo "{----}"
echo "{--42--}" && sysctl net.ipv4.conf.default.secure_redirects;echo "{----}"
echo "{--43--}" && sysctl net.ipv4.conf.all.accept_redirects;echo "{----}"
echo "{--44--}" && sysctl net.ipv4.conf.default.accept_redirects;echo "{----}"
echo "{--45--}" && sysctl net.ipv4.conf.all.accept_source_route;echo "{----}"
echo "{--46--}" && sysctl net.ipv4.conf.default.accept_source_route;echo "{----}"
echo "{--47--}" && sysctl net.ipv4.icmp_ignore_bogus_error_responses;echo "{----}"
echo "{--48--}" && sysctl net.ipv4.icmp_echo_ignore_broadcasts;echo "{----}"
echo "{--49--}" && sysctl net.ipv4.conf.all.log_martians;echo "{----}"
echo "{--50--}" && sysctl net.ipv4.conf.all.rp_filter;echo "{----}"
echo "{--51--}" && sysctl net.ipv4.conf.default.rp_filter;echo "{----}"
echo "{--52--}" && sysctl net.ipv4.tcp_syncookies;echo "{----}"
echo "{--53--}" && cat $PROC_NET_DEV|grep -iE "wlan|wifi";echo "{----}"
echo "{--54--}" && cat $NTP|grep -E "^server";echo "{----}"



